name: Run Sweeper

on:
  schedule:
    - cron: "0 * * * *" # Run every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  run-sweeper:
    runs-on: ubuntu-latest

    steps:
      - name: Call sweeper endpoint
        run: |
          curl -X POST https://hbd.bot/run-sweeper \
            -H "Authorization: Bearer ${{ secrets.ADMIN_TOKEN }}"
